/*
 * 履历管理子路由
 * */
let pagePedigreeAcceptance=()=>import(/*webpackChunkName:'acceptance'*/ '@/views/pedigree/acceptance')

export default [{
        path:"acceptance",
        name:"acceptance",
        component:pagePedigreeAcceptance,
        meta:{isReq:true}
    },{
        path:"natureData",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"natureBigth",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"verDict",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"special",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"modify",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"adjunct",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"reason",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"record",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"graveChange",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"seal",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"tearInstall",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"cycleIndex",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"memorandum",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"carryOut",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"workTime",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"argument",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"maintain",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"period",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"partsList",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"space",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"accept",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"grease",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"spectrum",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"Fault",
        component:pagePedigreeAcceptance,
        meta:""
    },{
        path:"DataList",
        component:pagePedigreeAcceptance,
        meta:""
}]